### ISSUE TITLE
Epic: Criar ambiente de testes

### ISSUE THREAD

**Issue by ericcastoldi** [ericcastoldi/Stag#8]
Criar automaticamente o ambiente para testes manuais de uma tarefa:
- [x] Definir a versão de compilação nos AssemblyInfo (5.8.8.92)
- [x] Compilar
- [x] Rodar o configurador e criar banco de dados (bem como alterar os web configs)
- [ ] Criar filial automaticamente (com certificado digital, proprietária e criando a pasta de integração)
- [x]  Abrir a solution no visual studio para que seja iniciado o debug

**Comment by ericcastoldi** [comment]
Closed by 1c02d2a0844e930cbe894e2531af037fb5ca2b34
